### ISSUE TITLE
Widget causing white screen and JS error in 5.21+

### ISSUE THREAD

**Issue by tieniber** [mendix/BootstrapTooltip#3]
When widget bundling is enabled, this widget causes the entire app not to render. The app throws a javascript error to the console:

`TypeError: Cannot read property 'jquery' of undefined {}`

coming from mxui.js. Based on some troubleshooting, it seems this line is the culprit:

`$ = tooltip.createInstance($);`

**Comment by tieniber** [comment]
Link to [mxforum post](https://mxforum.mendix.com/questions/9343/BootstrapTooltip-widget-working-locally-but-not-in-Sandbox)

**Comment by JelteMX** [comment]
Could you please check whether this updated version works or not? https://github.com/mendix/BootstrapTooltip/raw/bugfix/white_screen_js_error_5.21/test/widgets/BootstrapTooltip.mpk

**Comment by tieniber** [comment]
Yes! It's working in my 5.21 test project.

**Comment by tieniber** [comment]
I ran into an error when combining this widget into my other project with other widgets. The issue seemed to be with the assignment of the $ variable, effectively I believe another widget had reassigned $ to a different jQuery library instead of the one extended by the tooltip widget.

I was able to make things work by changing:

`$ = tooltip.createInstance(_jQ);`

to

`var j$ = tooltip.createInstance(_jQ);`

and then editing the 2 usages of $ to j$ in the _initializeTooltip function.

**Comment by JelteMX** [comment]
Well yes and no. Following the AMD structure using require, $ would be only valid in the scope of the widget. So it shouldn't be a problem. But, and this is what we're doing wrong here is not defining $ as a local variable:
```
$ = tooltip.createInstance(_jQ);
```
will define the global $ (window.$) as an instance of jQuery. It should be
```
var $ = tooltip.createInstance(_jQ);
```
as we define $ as a local variable within the scope of the widget

Your solution works as well I guess. Will generate a new version using that one

**Comment by JelteMX** [comment]
I generated a new one. Will update ```master``` branch with this solution and create a new release for the AppStore
