### ISSUE TITLE
Tooltip does not refresh on change of context entity

### ISSUE THREAD

**Issue by ivosturm** [mendix/BootstrapTooltip#9]
Also, jQuery is used to add the tooltip. jQuery is not needed for the Bootstrap tooltip. Would be best to just use plain JS and use bootstrap CSS classes to cater for tooltip functionality :). I have a working example if needed.

**Comment by ivosturm** [comment]
Hi Jelte, 

Can both proposed fixes be implemented?

**Comment by rik-bos** [comment]
Hi Jelte,

I see that pull request #10 fixes the refresh issue. Could you maybe merge and deploy that to the App Store?

Thanks!

Rik

**Comment by rickyv3** [comment]
Hi @rik-bos,

Were you able to fix this issue?

Thanks you!
Ricky

**Comment by rik-bos** [comment]
Hi @rickyv3,

Unfortunately I don't have the build on my machine, but I'm assuming that https://github.com/henkjanvanhenten/BootstrapTooltip/blob/master/test/widgets/BootstrapTooltip.mpk (the one that's from the pull request), should fix the issue for you.

If not, let me know (or @JelteMX may be able to pull in the request).

Rik

**Comment by rickyv3** [comment]
Hello @JelteMX ,

Could you pull in the request? Much appreciated!

-Ricky
